import React from "react";
import FilterWithSearch from "@/components/FilterWithSearch";

const top100Cities = [
  "Tokyo",
  "Jakarta",
  "Delhi",
  "Guangzhou-Foshan",
  "Mumbai",
  "Manila",
  "Shanghai",
  "Seoul-Incheon",
  "Cairo",
  "Mexico City",
  "Kolkata",
  "São Paulo",
  "New York",
  "Karachi",
  "Dhaka",
  "Bangkok",
  "Beijing",
  "Moscow",
  "Shenzhen",
  "Buenos Aires",
  "Los Angeles",
  "Johannesburg",
  "Bangalore",
  "Chengdu",
  "Ho Chi Minh City",
  "Osaka-Kobe-Kyoto",
  "Lagos",
  "Istanbul",
  "Lahore",
  "Kinshasa",
  "Tehran",
  "Chongqing",
  "Rio de Janeiro",
  "Xiʼan",
  "Chennai",
  "Paris",
  "Zhengzhou",
  "Luanda",
  "London",
  "Dongguan",
  "Lima",
  "Wuhan",
  "Bogotá",
  "Tianjin",
  "Hyderabad",
  "Taipei",
  "Hangzhou",
  "Nagoya",
  "Kuala Lumpur",
  "Chicago",
  "Nanjing",
  "Riyadh",
  "Shenyang-Fushun",
  "Ahmadabad",
  "Dar es Salaam",
  "Washington",
  "Boston",
  "Onitsha",
  "Bandung",
  "Addis Ababa",
  "Khartoum",
  "Santiago",
  "Dallas",
  "Nairobi",
  "San Francisco",
  "San Jose",
  "Toronto",
  "Pune",
  "Madrid",
  "Essen-Düsseldorf",
  "Quanzhou",
  "Houston",
  "Baghdad",
  "Surat",
  "Amman",
  "Surabaya",
  "Hong Kong",
  "Yangon",
  "Hanoi",
  "Qingdao",
  "Miami",
  "Suzhou",
  "Singapore",
  "Philadelphia",
  "Accra",
  "St. Petersburg",
  "Atlanta",
  "Abidjan",
  "Kabul",
  "Alexandria",
  "Milan",
  "Jiddah",
  "Ankara",
  "Faisalabad",
  "Barcelona",
  "Xiamen",
  "Belo Horizonte",
  "Taiyuan",
  "Changsha",
  "Hefei",
  "Mashhad",
  // Major Tech Cities
  "Cupertino",
  "Mountain View",
  "Palo Alto",
  "Menlo Park",
  "Sunnyvale",
  "Santa Clara",
  "Redmond",
  "Seattle",
  "Bellevue",
  "Austin",
  "Boulder",
  "Portland",
  "Raleigh",
  "Durham",
  "Tel Aviv",
  "Dublin",
  "Munich",
  "Stockholm",
  "Amsterdam",
  "Cambridge",
  "Waterloo",
  "Fremont",
  "Milpitas",
  "Denver",
  "Los Gatos",
];

const FilterByCity: React.FC = () => {
  return (
    <FilterWithSearch
      filterKey="city"
      filterDisplayKey="City"
      placeholder="Search cities"
      filterOptions={top100Cities}
    />
  );
};

export default FilterByCity;
