import React from "react";
import FilterWithSearch from "@/components/FilterWithSearch";

const top100Countries = [
  { country_name: "India", flag: "🇮🇳" },
  { country_name: "China", flag: "🇨🇳" },
  { country_name: "United States", flag: "🇺🇸" },
  { country_name: "Indonesia", flag: "🇮🇩" },
  { country_name: "Pakistan", flag: "🇵🇰" },
  { country_name: "Nigeria", flag: "🇳🇬" },
  { country_name: "Brazil", flag: "🇧🇷" },
  { country_name: "Bangladesh", flag: "🇧🇩" },
  { country_name: "Russia", flag: "🇷🇺" },
  { country_name: "Ethiopia", flag: "🇪🇹" },
  { country_name: "Mexico", flag: "🇲🇽" },
  { country_name: "Japan", flag: "🇯🇵" },
  { country_name: "Egypt", flag: "🇪🇬" },
  { country_name: "Philippines", flag: "🇵🇭" },
  { country_name: "Democratic Republic of the Congo", flag: "🇨🇩" },
  { country_name: "Vietnam", flag: "🇻🇳" },
  { country_name: "Iran", flag: "🇮🇷" },
  { country_name: "Turkey", flag: "🇹🇷" },
  { country_name: "Germany", flag: "🇩🇪" },
  { country_name: "Thailand", flag: "🇹🇭" },
  { country_name: "Tanzania", flag: "🇹🇿" },
  { country_name: "United Kingdom", flag: "🇬🇧" },
  { country_name: "France", flag: "🇫🇷" },
  { country_name: "South Africa", flag: "🇿🇦" },
  { country_name: "Italy", flag: "🇮🇹" },
  { country_name: "Kenya", flag: "🇰🇪" },
  { country_name: "Myanmar", flag: "🇲🇲" },
  { country_name: "Colombia", flag: "🇨🇴" },
  { country_name: "South Korea", flag: "🇰🇷" },
  { country_name: "Sudan", flag: "🇸🇩" },
  { country_name: "Uganda", flag: "🇺🇬" },
  { country_name: "Spain", flag: "🇪🇸" },
  { country_name: "Algeria", flag: "🇩🇿" },
  { country_name: "Iraq", flag: "🇮🇶" },
  { country_name: "Argentina", flag: "🇦🇷" },
  { country_name: "Afghanistan", flag: "🇦🇫" },
  { country_name: "Yemen", flag: "🇾🇪" },
  { country_name: "Canada", flag: "🇨🇦" },
  { country_name: "Angola", flag: "🇦🇴" },
  { country_name: "Ukraine", flag: "🇺🇦" },
  { country_name: "Morocco", flag: "🇲🇦" },
  { country_name: "Poland", flag: "🇵🇱" },
  { country_name: "Uzbekistan", flag: "🇺🇿" },
  { country_name: "Malaysia", flag: "🇲🇾" },
  { country_name: "Mozambique", flag: "🇲🇿" },
  { country_name: "Ghana", flag: "🇬🇭" },
  { country_name: "Peru", flag: "🇵🇪" },
  { country_name: "Saudi Arabia", flag: "🇸🇦" },
  { country_name: "Madagascar", flag: "🇲🇬" },
  { country_name: "Côte d'Ivoire", flag: "🇨🇮" },
  { country_name: "Cameroon", flag: "🇨🇲" },
  { country_name: "Nepal", flag: "🇳🇵" },
  { country_name: "Venezuela", flag: "🇻🇪" },
  { country_name: "Niger", flag: "🇳🇪" },
  { country_name: "Australia", flag: "🇦🇺" },
  { country_name: "North Korea", flag: "🇰🇵" },
  { country_name: "Syria", flag: "🇸🇾" },
  { country_name: "Mali", flag: "🇲🇱" },
  { country_name: "Burkina Faso", flag: "🇧🇫" },
  { country_name: "Sri Lanka", flag: "🇱🇰" },
  { country_name: "Taiwan", flag: "🇹🇼" },
  { country_name: "Malawi", flag: "🇲🇼" },
  { country_name: "Zambia", flag: "🇿🇲" },
  { country_name: "Chad", flag: "🇹🇩" },
  { country_name: "Kazakhstan", flag: "🇰🇿" },
  { country_name: "Chile", flag: "🇨🇱" },
  { country_name: "Somalia", flag: "🇸🇴" },
  { country_name: "Senegal", flag: "🇸🇳" },
  { country_name: "Romania", flag: "🇷🇴" },
  { country_name: "Guatemala", flag: "🇬🇹" },
  { country_name: "Netherlands", flag: "🇳🇱" },
  { country_name: "Ecuador", flag: "🇪🇨" },
  { country_name: "Cambodia", flag: "🇰🇭" },
  { country_name: "Zimbabwe", flag: "🇿🇼" },
  { country_name: "Guinea", flag: "🇬🇳" },
  { country_name: "Benin", flag: "🇧🇯" },
  { country_name: "Rwanda", flag: "🇷🇼" },
  { country_name: "Burundi", flag: "🇧🇮" },
  { country_name: "Bolivia", flag: "🇧🇴" },
  { country_name: "Tunisia", flag: "🇹🇳" },
  { country_name: "South Sudan", flag: "🇸🇸" },
  { country_name: "Haiti", flag: "🇭🇹" },
  { country_name: "Belgium", flag: "🇧🇪" },
  { country_name: "Jordan", flag: "🇯🇴" },
  { country_name: "Dominican Republic", flag: "🇩🇴" },
  { country_name: "United Arab Emirates", flag: "🇦🇪" },
  { country_name: "Honduras", flag: "🇭🇳" },
  { country_name: "Cuba", flag: "🇨🇺" },
  { country_name: "Tajikistan", flag: "🇹🇯" },
  { country_name: "Papua New Guinea", flag: "🇵🇬" },
  { country_name: "Sweden", flag: "🇸🇪" },
  { country_name: "Czechia", flag: "🇨🇿" },
  { country_name: "Portugal", flag: "🇵🇹" },
  { country_name: "Azerbaijan", flag: "🇦🇿" },
  { country_name: "Greece", flag: "🇬🇷" },
  { country_name: "Togo", flag: "🇹🇬" },
  { country_name: "Hungary", flag: "🇭🇺" },
  { country_name: "Israel", flag: "🇮🇱" },
  { country_name: "Austria", flag: "🇦🇹" },
  { country_name: "Belarus", flag: "🇧🇾" },
  { country_name: "Remote", flag: "🌍" },
];

const FilterByCountry: React.FC = () => {
  // Format the country options with display (flag + name) and value (just name)
  const countryOptions = top100Countries.map((country) => ({
    display: `${country.flag} ${country.country_name}`,
    value: country.country_name,
  }));

  return (
    <FilterWithSearch
      filterKey="country"
      filterDisplayKey="Country"
      placeholder="Search countries"
      filterOptions={countryOptions}
    />
  );
};

export default FilterByCountry;
